name = "Comparator"
version = "0.1.0"
defaultTargets = ["comparator"]

[[lean_lib]]
name = "Comparator"

[[lean_exe]]
name = "comparator"
root = "Main"

[[require]]
scope = "leanprover"
name = "Lean4Checker"
rev = "b7398199245524275543dec6113229c9bb4902e5"

[[require]]
name = "lean4export"
git = "https://github.com/augustepoiroux/lean4export"
rev = "d17578b17b86a30986e4536284c32e90b9b52812"
